spring:
  application:
    name: Pet-Pedia

  datasource:
    url: jdbc:mysql://pet-pedia-database.cz0w4iki8hg5.us-east-2.rds.amazonaws.com:3306/pet-pedia-database
    username: admin
    password: fecbaf-beZviz-5korjo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update